### ISSUE TITLE
decide where the X goes and where it does not

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/rom-tools-and-workflows#110]
<img width="734" alt="image" src="https://github.com/Pressio/rom-tools-and-workflows/assets/18708772/bec516d7-cfcc-4655-8d29-3bf604a48e2a">

need to decide if the X defines a product or just indicates a new axis

**Comment by eparish1** [comment]
@fnrizzi I think that \times should always denote a new axis and not a product, which is consistent with most mathematical notation that I've seen. Not sure if people have other thoughts on this.
