### ISSUE TITLE
public vs private  `tensor_to_matrix(tensor_input)`

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/rom-tools-and-workflows#111]
do we need this to be public?

`def tensor_to_matrix(tensor_input):`
`def matrix_to_tensor`

**Comment by jtencer** [comment]
Do we use it anywhere outside of that file?

**Comment by fnrizzi** [comment]
no, but the questions is whether we want to expose this or not. I don't think we should. We should make it private and MAYBE expose it later if tehre is a real need for it

**Comment by eparish1** [comment]
@fnrizzi I think we should make it private, I see no real need to expose it at the moment.

**Comment by fnrizzi** [comment]
i agree, i will do that
