### ISSUE TITLE
Combine TrialSpaceFromPOD and TrialSpaceFromScaledPOD

### ISSUE THREAD

**Issue by jtencer** [Pressio/rom-tools-and-workflows#121]
add an optional `scaler` argument to `TrialSpaceFromPOD` with a default value of `NoOpScaler()` and delete `TrialSpaceFromScaledPOD`

**Comment by jtencer** [comment]
Recent renaming has changed "trial" to "vector" for the above-mentioned classes and modules.

**Comment by fnrizzi** [comment]
https://github.com/Pressio/rom-tools-and-workflows/pull/129
