### ISSUE TITLE
ConstantShifter should accept a number

### ISSUE THREAD

**Issue by jtencer** [Pressio/rom-tools-and-workflows#131]
ConstantShifter currently accepts a numpy array of values (one for each variable).  This is fine, but for cases in which there is only one variable or when all variables should be shifted by the same value, it is unnecessary and confusing.  ConstantShifter should also accept a number in those cases and should not result in an error when passed a number.

**Comment by cwschilly** [comment]
Should I incorporate this into PR #118 ?

**Comment by eparish1** [comment]
@cwschilly That would be great if you can!
