### ISSUE TITLE
replacing `svd` and calling the svd in linalg library

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/rom-tools-and-workflows#138]
IMO, in the pressio linalg library we should offer a function: `linalg.thin_svd(matrix)` that internally computes the thin svd but uses some heurtiastics for the best algorithm to use
 
And then in romtools we should do:

- inside `VectorSpaceFromPOD` we should call `linalg.thin_svd(matrix)` 
- get rid of the method of snapshot and move it inside linalg as one of the possible methods to use

**Comment by fnrizzi** [comment]
so basically inside pressio linalg we would have: 
```py
def thin_svd(matrix, comm=None):
   # if comm is none or size is 1, do scipy or similar 
   # if matrix is distributed but condition A applies, usse algorithm A
   # if matrix is distributed but condition B applies, usse algorithm B
   # if condiiton number is ... , use that 
   # ... 
```   
we obviously would refine this as needed and based on expeirence

**Comment by fnrizzi** [comment]
doing this allows us to move away the logic of how we do the best svd from romtools to the lingalg library. 
rationale is that suppose that we had a magic function that to compute svd that is guaranteed to work well always, we would alwasy do that

**Comment by eparish1** [comment]
I'm fine with this, as long as the user can force-specify their method if they want.

**Comment by fnrizzi** [comment]
done
