### ISSUE TITLE
Change get_dimension in vector_space

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows#139]
In vector_space, we presently use:
`self.__dimension = self.__basis.shape[2]`

For a variety of downstream issues, it will be better to have this be

`self.__dimension = self.__basis.shape`

@jtencer @fnrizzi @pjb236 @ekrathSNL  Any issues with this?

**Comment by fnrizzi** [comment]
i dont see the difference  in those two?

**Comment by eparish1** [comment]
@fnrizzi Sorry, fixed. The second one should return the full shape.

**Comment by fnrizzi** [comment]
if we want to store the shape can we call it shape? or maybe `extents`?

**Comment by fnrizzi** [comment]
i am also fine with dimension but i think that conflicts with what we call dimension colloquially for the trial vector space

**Comment by eparish1** [comment]
Yeah, I'm fine with any of the above. We use extent in pressio, right?

**Comment by fnrizzi** [comment]
> Yeah, I'm fine with any of the above. We use extent in pressio, right?

yes

**Comment by eparish1** [comment]
Ok, I propose we change `get_dimension` to `extents`. Everyone good with this?

**Comment by fnrizzi** [comment]
yes i am
