### ISSUE TITLE
Basis read capability

### ISSUE THREAD

**Issue by pjb236** [Pressio/rom-tools-and-workflows#162]
Currently we have the capability to write a basis to several open source formats in vector_space/utils/outputter.py. It would be helpful in a number of the hyper-reduction workflows to have corresponding read capabilities. Should we provide this as well?

**Comment by jtencer** [comment]
I wrote something to do this in the aria-tools repo in the `state_reconstructor` branch.  I just merged it into main so it should be available there now.

**Comment by pjb236** [comment]
@jtencer That's exactly what I had in mind. I'm wondering if we want to have something like "BasisFromExodus" in rom-tools-and-workflows, along with readers for npc and hdf5 formats that we currently support output to. @eparish1, @fnrizzi what do you think?

**Comment by jtencer** [comment]
I think this aligns with a larger discussion we need to have to have about io support, and especially exodus and hdf5 support since those involve external dependencies.
