### ISSUE TITLE
Running ROM or residual postprocessing for cases corresponding to existing FOM runs

### ISSUE THREAD

**Issue by pjb236** [Pressio/rom-tools-and-workflows#163]
The coupler requires a parameterSampler which is used to populate an array of parameter samples, but in many cases we need to run cases on the same set of samples. These cases include:

1. Running the FOM and ROM at the same points to compute test set errors or correlations for multi-fidelity UQ. 
2. Running a post-processor to compute residual snapshots (and/or test basis snapshots) to provide data for ECSW or DEIM hyper-reduction approaches. 

In these cases, being able to provide a list of existing case directories from which to obtain parameter and potentially solution data would be helpful. This would be very similar to the coupler, but with no need for a parameterSampler as far as I can see.

**Comment by eparish1** [comment]
We will re-review this once the workflows w/ the model have been updated.

**Comment by pjb236** [comment]
@eparish1 Sounds good, I'll try redoing my Aria workflow with the new model class. @jtencer let me know when you plan on updating the main branch of aria_tools to use model instead of the coupler.

**Comment by jtencer** [comment]
I'll need to wait to update the ariatools stuff until we update the `SamplingCouplerBase`.  I've been trying not to get ahead of the romtools develop branch because ariatools relies on romtools.
