### ISSUE TITLE
Add vector_space_builder class

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows#167]
With our updates to models, the "GreedyCoupler" is now dead. Previously, this coupler had the logic for creating the trial space, so now we need a new approach. I propose we create a stand alone class for this. I propose something like this:

```

'''
Protocol for building a trial space for use in workflow algorithms 
'''

from pathlib import Path
from typing import Protocol


class VectorSpaceBuilder(Protocol):
    '''
    Baseline protocol 
    '''
    def __init__(self) -> None:
        '''
        Initialize 
        '''
        pass

    def build_and_save_vector_space_from_list_of_directories(self, save_directory: str, list_of_directories: list) -> None:
        '''
        This function should build a vector space from a list of directories and save it to file for use
        '''
        pass

```

**Comment by jtencer** [comment]
I think you likely need an additional protocol in between that handles some file io stuff.  On the aria side, I have a class `ExodusSnapshotManager` that handles that bit that looks like this:

```Python
class ExodusSnapshotManager():
    def __init__(self, filenames: Iterable[str], var_names: Iterable[str]) -> None:
        self._input_filenames = filenames
        self._var_names = var_names
        self._snapshots = self._read_snapshots()

    def get_snapshot_tensor(self) -> np.ndarray:
        '''
        Returns numpy tensor of shape N_vars x N_space x N_samples

        Returns:
            np.ndarray of shape (N_vars, N_space, N_samples)
        '''
        return self._snapshots

    def get_exodus_template(self) -> str:
        '''
        Returns template exodus file for writing results based on snapshot data
        '''
        return self._input_filenames[0]

    def get_variable_names(self) -> Iterable[str]:
        '''
        Returns list of variable names
        '''
        return self._var_names

    def _read_snapshots(self) -> np.ndarray:
        s = [_read_exodus(filename, self._var_names)
             for filename in self._input_filenames]
        return np.concatenate(s, axis=2)


def _read_exodus(filename: str, var_names: Iterable[str]) -> np.ndarray:
    '''
    Read in snapshot data from a single exodus file
    '''
    exo = exodus.exodus(filename, array_type='numpy', mode='r')

    _check_var_names(exo, var_names)

    snapshots = np.zeros((len(var_names), exo.num_nodes(), exo.num_times()))
    for timestep in range(snapshots.shape[2]):
        for var_idx, var_name in enumerate(var_names):
            nodal_values = exo.get_node_variable_values(var_name, timestep+1)
            snapshots[var_idx, :, timestep] = nodal_values
    exo.close()

    return snapshots


def _check_var_names(exo, var_names: Iterable[str]) -> None:
    '''
    Confirm all names in var_list are in the exodus file
    '''
    if not set(var_names).issubset(set(exo.get_node_variable_names())):
        print("Variable names requested:")
        print(f"    {var_names}")
        print("Variable names available:")
        print(f"    {exo.get_node_variable_names()}")
        raise KeyError("All variables in list not included in exodus file")
```

Downstream from that you can use it like
```Python
space = VectorSpaceFromPOD(snapshots=snapshots.get_snapshot_tensor(),
                           shifter=create_firstvec_shifter(my_array=snapshots.get_snapshot_tensor()),
                           truncater=BasisSizeTruncater(basis_dimension=4))
```
which lets you use all the different options for creating a `VectorSpace` rather than being restricted by whatever arguments your `VectorSpaceBuilder` protocol supports.

**Comment by eparish1** [comment]
@jtencer  Wouldn't this just be a specific implementation of the above though? I could define a basis manger/constructor relevant for my application, which basically has all of the stuff that you put above, and then you just provide the interface for the build_and_save_vector_space_from_list_of_directories either by defining another class, or even wrapping it into the manager. 

I agree there is a lot of "in between" things to do like io, basis construction, etc., but I think these would be details of the implementation rather than something we handle on our end.

**Comment by jtencer** [comment]
Sorta.  The difference I'm seeing is where you put the interface.  In the above, you're basically wrapping the `VectorSpace` constructor which I don't love because you have to reproduce all the options and all the work is still on the user side.  I think it makes more sense for the interface between romtools and the application specific piece to be at the level of handling the io.  If you had that, you could potentially simplify the `VectorSpace` constructor call by not passing snapshot info into all the different `*er` objects that you use but rather handling that inside the `VectorSpace` constructor in a consistent way.

So I guess what I'm proposing is something that gets you a snapshot tensor from a list of directories or files rather than something that gets you a `VectorSpace` from a list of directories or files.

**Comment by eparish1** [comment]
@jtencer I guess I'm confused why you wouldn't just do this?

```

class MyVectorSpaceBuilder:
    def __init__(self,snapshot_manager):
        ## do necessary inits
        self.snapshot_manager = snapshot_manager

    def build_vector_space_from_list_of_dirs(list_of_dirs):
        snapshots = self.snapshots_manager.get_snapshots_from_list_of_dirs(list-of_dirs)
        VectorSpace = VectorSpaceFromPod(snapshots)
        #save to file



```
As an alternative, it seems like you're proposing two classes, one for reading, and one for constructing? I guess I don't see the motivation for this? The user has to define their own vector space implementation regardless, it just seems to be a question of how to wrap it when passed to, e.g., greedy.

**Comment by jtencer** [comment]
Yeah. I think that having an API for some sort of data reader would be useful and could simplify some of the vector space construction stuff. That's a little bit orthogonal to the greedy thing. 

For that, I think you just need a function that takes in a data reader and returns a VectorSpace. The function could even just be the constructor for a VectorSpace implementation. I'm not sure we need a class just for that.

**Comment by rloekvh** [comment]
Interested in this as part of #170. I’ve gone back and forth on this a few times and chatted with @pjb236 about this yesterday, but I think at least the name might be confusing. 

vector_space_builder makes me think this is a necessary method of a VectorSpace class, and that it is responsible for “building” a vector space from FOM snapshots i.e. identifying the snapshots _and_ performing actions like shifting, scaling, SVD, etc. So to me it sounds like it should be a VectorSpace constructor. I think I'm confused about what the minimal functionality should be. 

One question I have: can this be run without a user-defined VectorSpace? If not, would it make sense for it to be a method for a VectorSpace?

**Comment by eparish1** [comment]
@rloekvh I agree the name is confusing.

The purpose for this function IMO should be to construct a basis given directories that have FOM solutions. This could be a vector_space as we define in rom-tools, or it could be some completely external thing. The goal is that, after the function has been called, a basis exists in a location defined by the user which they can then use for their ROMs. 

Presently, my perspective is to have the user define something like what I put three comments above. I like this rather than having classes/functions get passed that explicitly have IO because of how much this complicates things. For example, how do we handle saving the basis to file? Do we add another method save_vector_space_to_file to the VectorSpace class? This becomes complicated because the base classes are basically always now abstract. We could instead define another protocol for VectorSpace equipped with methods to save and load. All of these seem to get complicated and confusing, which is why I was thinking more like the above, but I'm very open to discuss this. 

@jtencer @pjb236 @fnrizzi @ekrathSNL  We should discuss this next monday.

**Comment by jtencer** [comment]
I won't be around tomorrow, but it's worth noting that we already have functions for saving vector spaces to file.  Talking about how much we want to support that has been a TODO though so it's definitely not settled. 

One thing that might enable us to make the workflow generic while still supporting a variety of vector space construction options could be to accept a vector space constructor and a kwargs dictionary.
