### ISSUE TITLE
add arg max for distributed case

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/rom-tools-and-workflows#184]
```py
def mycomp(a,b,dt):
    if a[0] < b[0]:
      return b[1]
    else:
      return a[1] 



def my_arg_max(U,comm):
    local_max_index = np.argmax(U,axis=0)
    local_max_val = np.max(U,axis=0)
    a = np.zeros(3)
    a[0] = local_max_val
    a[1] = local_max_index
    a[2] = comm.Get_rank()

    result = np.zeros(3)
    myop = MPI.Op.Create(mycomp, commute=False)
    comm.Allreduce(a,result,op=myop)
    return result 
```    
just a sketch of what it can look like because for distributed case local index is not sufficient to identify the element

**Comment by fnrizzi** [comment]
@cwschilly ideally we should change the array and use a custom struct of similar if possible

**Comment by fnrizzi** [comment]
@cwschilly is this progressing?

**Comment by fnrizzi** [comment]
we need to ensure this holds: In case of multiple occurrences of the maximum values, the indices corresponding to the first occurrence are returned.

so in our case, we need to return the local index corresponding to the *smallest* rank (this is because we decide this not any particular thing)

**Comment by cwschilly** [comment]
> @cwschilly is this progressing?

Hi @fnrizzi yes, hoping to wrap up by end of day
