### ISSUE TITLE
Scalar scaler

### ISSUE THREAD

**Issue by jtencer** [Pressio/rom-tools-and-workflows#192]
Need a scalar version of `VectorScaler` because the use case is common and passing a number to `VectorScaler` results in an error.  Also the name `ScalarScaler` brings me joy.

something like 
```python
class ScalarScaler:
    """
    Applies a scalar scale factor

    This class conforms to `Scaler` protocol.
    """

    def __init__(self, factor: float = 1.0) -> None:
        self._factor = factor

    def pre_scale(self, data_tensor):
        return data_tensor / self._factor

    def post_scale(self, data_tensor):
        return data_tensor * self._factor
```

**Comment by eparish1** [comment]
@jtencer I'm fine with this. I envisioned people just extending the scalar into a vector, but I'm good w/ doing a dedicated one for the scalar. I agree the name is excellent.
