### ISSUE TITLE
summary of current tests: w or w/o MPI, ranks, etc

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/rom-tools-and-workflows#20]
make a summary of all tests currently present in the code so that we have an idea of which ones are serial, which ones use MPI, how many ranks ,etc 
something like: 
- test_name1: serial, skipped with mpi
- test_name2: mpi, min # ranks 3 else no-op
- test_name3: mpi, min # ranks 3 
etc

**Comment by cwschilly** [comment]
## All tests found in tests/romtools

### hyper_reduction
test_diem.py (SERIAL)
1. `test_diem_approximation()`: serial
2. `test_deim_basis()`: serial
3. `test_full_deim()`: serial
---
### test_trial_space_utils
test_orthogonalizer.py (SERIAL, SKIPPED WITH MPI)

4. `test_noop_orthogonalizer()`: serial, skipped with mpi
5. `test_euclidean_l2_orthogonalizer()`: serial, skipped with mpi
6. `test_euclidean_vector_weighted_l2_orthogonalizer()`: serial, skipped with mpi

test_scaler.py (SERIAL, SKIPPED WITH MPI)

7. `test_noop_scaler()`: serial, skipped with mpi
8. `test_vector_scaler()`: serial, skipped with mpi
9. `test_variable_scaler()`: serial, skipped with mpi
10. `test_variable_and_vector_scaler()`: serial, skipped with mpi

test_shifter.py (SERIAL, SKIPPED WITH MPI)

11. `test_noop_shifter()`: serial, skipped with mpi
12. `test_constant_shifter()`: serial, skipped with mpi
13. `test_average_shifter()`: serial, skipped with mpi
14. `test_first_vec_shifter()`: serial, skipped with mpi
15. `test_vector_shifter()`: SKIPPED

test_splitter.py (SERIAL, SKIPPED WITH MPI)

16. `test_noop_splitter()`: serial, skipped with mpi
17. `test_block_splitter_order_f()`: serial, skipped with mpi
18. `test_block_splitter_order_c()`: serial, skipped with mpi

test_svd_kernel_trick_mpi.py

19. `test_parallel_kernel_trick_on_three_cores()`: mpi, min # ranks 3 else no-op
20. `test_class_parallel_kernel_trick_on_three_cores()`: mpi, min # ranks 3 else no-op

test_truncater.py

21. `test_noop_truncater()`: serial, skipped with mpi
22. `test_basis_size_truncater()`: serial, skipped with mpi
23. `test_energy_truncater()`: serial, skipped with mpi
---
### workflows/greedy

24. `test_greedy_coupler_builder()`: serial, skipped with mpi
25. `test_greedy()`: serial, skipped with mpi
---
### workflows/sampling

26. `test_sampler_builder()`: serial, skipped with mpi
27. `test_sampler()`: serial, skipped with mpi
---
### test/romtools

test_demo1

28. `test_demo1()`: serial, skipped with mpi

test_snapshots_mpi.py

29. `test_mpi_snapshots()`: mpi, min # ranks 3 else no-op

test_trial_space_svd_mpi.py

30. `test_trial_space_from_pod_mpi()`: mpi, min # ranks 3

test_trial_space.py

31. `test_dictionary_trial_space()`: serial, skipped with mpi
32. test_trial_space_from_pod()`: serial, skipped with mpi
33. `test_trial_space_from_scaled_pod()`: serial, skipped with mpi
34. `test_list_snapshots_to_array()`: SKIPPED

SUMMARY:

| Type     | Number |
| ----------- | ----------- |
| Serial      | 28 |
| MPI   | 4  |
| Skipped | 2 |
