### ISSUE TITLE
testing with mpi: decide on a min/max # of ranks 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/rom-tools-and-workflows#21]
we need to decide if tests when run with mpi need to have a min/max # of ranks. 
For example we could:
- not set any rule on this: any test does whatever but then this creates an issue for the CI 
- decide only on the min # of ranks to use so that all MPI test should conform to this but then how do we set the # of ranks to use in the CI? 
- decide that every MPI test MUST be wirtten to work with a min and a max # of ranks

**Comment by eparish1** [comment]
I am a bit confused. Can we set a min and max set of ranks for the test, and then write it so that each test is written to work for the min-max range? In the simplest case we can just set min=max?

**Comment by jtencer** [comment]
I think we could probably be ok running them on 1 and 3 or 4. I don't think there's a lot of extra value in going larger or doing lots of different sizes and it would slow down CI.

**Comment by fnrizzi** [comment]
we can set min and max but we need to make sure the tests can run for that range. 
Look here: https://github.com/Pressio/rom-tools-and-workflows/issues/20, "All MPI tests must be run with n=3"
right now we are ding for example:

![image](https://github.com/Pressio/rom-tools-and-workflows/assets/18708772/7c1fccfc-0a02-4218-8360-4504910a8c1c)


this means that min is 3 but the test will be skipped for n>3.

**Comment by fnrizzi** [comment]
so we need to decide if we want to leave it that way or do something like this:

```
@pytest.mark.mpi
def test_mpi_snapshots():
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    # here we have to make it work for *ANY # of ranks*
```        
or 

```
@pytest.mark.mpi(min_size=3)
def test_mpi_snapshots():
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    if doing 3 ranks:
      # bla bla
   else:
     # bla blas
```        

```
@pytest.mark.mpi(min_size=3)
def test_mpi_snapshots():
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    if doing 3 ranks:
      # bla bla
   else:
     # do nthing
```

**Comment by eparish1** [comment]
I agree with this. I think running with 3 or 4 ranks is sufficient (I like 3 because it's an odd number personally), and just passing the test if we run with the wrong number or ranks.

**Comment by pjb236** [comment]
I also agree that 3 or 4 ranks is a good test of parallel capability. I also agree with skipping if the wrong number of ranks is used, maybe with some kind of warning that the test was not run.
