### ISSUE TITLE
Change greedy algorithm save file to include actual values of parameters

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows#65]
The greedy algorithm should save to file the actual values of the parameters it has run the FOM for. Right now, it just saves the sample index.

**Comment by fnrizzi** [comment]
https://github.com/Pressio/rom-tools-and-workflows/blob/main/romtools/workflows/greedy/run_greedy.py

**Comment by eparish1** [comment]
Thanks Francesco. Basically, on line 202 we should also save the "parameter_samples" array. This should be a 2D array of size N_samples x N_parameters. The N_samples dimension will grow at each iteration of the algorithm.

**Comment by fnrizzi** [comment]
@cwschilly if you have any issues/questios please reach out! thank you!
