### ISSUE TITLE
Reformat snapshot data to be in tensor form

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows#66]
As we discussed, we are going to refactor snapshot data to be in the form of a tensor:

snapshots \in \RR{ N_vars x N_gridpoints x N_samples }

Is everyone ok with this shape? 

Internally, when we leverage the snapshots to do, e.g., POD, we will reshape them into a matrix of size N_vars N_gridpoints x N_samples. We have the option of adapting order "F" convention to do this, or order "C" convention to do this. Order "F" will order the states as u_1, v_1,w_1, u_2,v_2, ...  , while "C" will block the variable sets.

I would vote for order "F", even though that's not the preferred way for Python. The alternative is to set up the snapshot shape as  snapshots \in \RR{ N_gridpoints x N_vars x N_samples }, in which case we could reshape with order "C" to have u_1, v_1,w_1, u_2,v_2,.

Any preferences?

**Comment by fnrizzi** [comment]
i have to think a bit about this. 
> I would vote for order "F", even though that's not the preferred way for Python. 

why not the preferred way? in what sense?

**Comment by fnrizzi** [comment]
I think that you are talking about performance, it could be useful to do a simple test with a random matrix with those two layouts and call svd on it as you say and compare. what do you think? 
or you are talking about something else?

**Comment by eparish1** [comment]
Python is order 'C' by default and stores in memory this way. I'd argue F reshape is more error prone since it's not the default, and it also might have a performance hit but I'm not positive about that.

**Comment by fnrizzi** [comment]
@cwschilly we should talk about this so that we can proceed

**Comment by cwschilly** [comment]
To time the difference between the two layouts, I am using this function:

```python
def singleRunSvd(n_vars, n_gridpoints, n_samples, layout, num_iters = 500):
    print(f"Creating tensor with size {n_vars} x {n_gridpoints} x {n_samples} and layout {layout}")
    M = np.asarray(np.random.rand(n_vars, n_gridpoints, n_samples), order=layout)

    svd_time = timeit.timeit(lambda: np.linalg.svd(M, full_matrices=False), number=num_iters)
    avg_time = svd_time / num_iters

    return avg_time
```

This is calling `np.linalg.svd` on a 3-D tensor, which causes the function to work in "stacked" mode, as explained in the [NumPy documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html):

> If a has more than two dimensions, then broadcasting rules apply, as explained in [Linear algebra on several matrices at once](https://numpy.org/doc/stable/reference/routines.linalg.html#routines-linalg-broadcasting). This means that SVD is working in “stacked” mode: it iterates over all indices of the first `a.ndim - 2` dimensions and for each combination SVD is applied to the last two indices. The matrix a can be reconstructed from the decomposition with either `(u * s[..., None, :]) @ vh` or `u @ (s[..., None] * vh)`. (The @ operator can be replaced by the function np.matmul for python versions below 3.5.)

Alternatively, I could test by reshaping the tensor into a matrix with shape `n_gridpoints * n_vars x n_samples` (as dicussed with @fnrizzi).

@eparish1 Should I continue with calling SVD on a 3-D tensor or reshape into a 2-D matrix?

**Comment by eparish1** [comment]
Sorry about the very slow responses, I'm going to pull and spend some time on this. 

We don't want to do an SVD of a tensor; the general thing we will want to do is take a tensor, reshape it into a matrix, and then do SVD on that. I don't expect there to be a significant performance difference either way.

**Comment by cwschilly** [comment]
Hi @eparish ,

Here are the results of performing svd on a tensor (I did this last month) with different layouts, n_vars, and n_gridpoints. Is it worth changing the script to reshape the tensor into a matrix, or do you think this is representative of the results either way?

![image](https://github.com/Pressio/rom-tools-and-workflows/assets/132086024/9680ef27-c1e5-4dfe-ac3d-903baadc77b8)

**Comment by eparish1** [comment]
Hi @cwschilly 

I wouldn't worry about this. The SVD on the tensor won't be representative of the SVD on the matrix, unfortunately. After looking into it a bit, the main overhead we encounter with the 'F' ordering will be a copy of the data in the reshaping (assuming the data is in default C python layout), which we will want to avoid. Sticking with the 'C' ordering is almost necessary because of this.
