### ISSUE TITLE
Linear algebra libraries: mpi4py light library and pressio-tools full library.

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows#70]
To add concrete implementations that can be run parallel (row distributed memory), we need a variety of basic algebra and linear algebra functions. 
We want to be able to create a new library that has two usages:
1. a "light mode": 
  - installable via `pip install ...` and has pure python dependencies (if any)
  - supports some of the basic functions so that a user can utilize most of the rom-tools library without headaches

2. a "heavy more performant mode": 
  - uses bindings to Trilinos building on top of what we have done already in https://github.com/Pressio/pressio-tools

NOTE: All functions should target **row distributed parallelization** 

**For the python-only library mode 1 we will support**
- min max of a distributed vector
- A^T B, where A and B are both row distributed
- Hacks to do the SVD and orthogonalization via method of snapshots
- Stretch/unlikely: svd, qr, basic linear solve.

**For the more heavy library mode 2 we will support**
- min max of a distributed vector
- A^T B, where A and B are both row distributed
- Hacks to do the SVD and orthogonalization via method of snapshots
- svd
- qr
- linear solve

**Comment by fnrizzi** [comment]
@cwschilly i will set up a meeting to discuss this

**Comment by fnrizzi** [comment]
we should try to come up with an interface that is similar to the numpy lingalg library with an extra argument for the MPI communicator

**Comment by eparish1** [comment]
@cwschilly Have you all been working on this at all? No worries if not, just wanted to check in on where this is at.

**Comment by cwschilly** [comment]
@eparish1 Yes the work has been done in [this repository](https://github.com/Pressio/pressio-linalg). So far we've been focusing on the Python-only implementation, but working regarding the C++ bindings is on the `implement-cpp-bindings` branch

**Comment by fnrizzi** [comment]
@eparish1 Caleb did pretty much all of the code in python. I suggested that we wait on the C++ binding stuff, because we first need to figure out if the API for the ops makes sense. to do so, we just need the python implementation that Caleb has done.

**Comment by eparish1** [comment]
@fnrizzi @cwschilly Could you update the pip build to grab the repo that this is being developed in? After that, we can start going through the code and making modifications for this.

**Comment by fnrizzi** [comment]
@eparish1 what do you mean by grab the repo?

**Comment by eparish1** [comment]
@fnrizzi Since the mpi stuff is in a different repo, the install for rom-tools will need to install this as well. Or did you have something else in mind?

**Comment by fnrizzi** [comment]
I thought we install this linalg library on its own. And then use it in tools

**Comment by fnrizzi** [comment]
You want the installation of romtools to automatically fetch the linalg? 
I think that contraditcs the fact that romtools isn't tied to a particular linalg one

**Comment by eparish1** [comment]
@fnrizzi We may need to touch base on this. I would like rom-tools to natively support basic mpi4py parallelism, or at least have it be an optional install. Having something like pressio-tools also be an optional install makes sense. What I don't want is for rom-tools to rely on a complex third party library with its own host of dependencies. 

In general, we need to start updating the code for changing certain operations to be in parallel, and developing parallel tests. Right now all of the scalers, for example, can't be run in parallel. To do this, I'd like to have the infrastructure set up to have a baseline parallel linalg package. Does this make sense?

**Comment by fnrizzi** [comment]
makes total sense! btw, the linalg library has been designed so far to have only a simple pure python depdency (beside mpi4py). If you want to make it an optional depe of romtools such that it is romtools that pottenailly fetches it, then yes we can talk!
