### ISSUE TITLE
Test failure in install-and-test.yaml from check-mpi-size.py 

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows#77]
@fnrizzi @cwschilly 

This part of the testing workflow is causing our tests to fail (seems this has been the case for a bit)

https://github.com/Pressio/rom-tools-and-workflows/actions/runs/7221756264/job/19677403724

I commented this out for now so that the tests would pass, but could one of you take a look whenever you have a chance? This is a bit beyond me :)

**Comment by cwschilly** [comment]
Closed with PR #78
