### ISSUE TITLE
Small ECSW improvements

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows#81]
- Update documentation for inputs/outputs to conform to the rest of the code
- Potentially use more expressive variable names (e.g., xi->weights, inds-> sample_mesh_indices, tau->tolerance). Thoughts?
- Is there any reason that xi is of size N instead of N_s?
- Could we make inds a numpy array instead of a list? I personally like this more, but this doesn't need to be the case.
- In the ecsw_fixed_test_basis, the default solver is the abstract solver. Should we change this to be the concrete implementation?

**Comment by pjb236** [comment]
@eparish1  I can take care of the first four items. For the last item, we are specifying an input of type AbstractECSWsolver; AbstractECSWsolver is not the default solver. This allows users to provide their own solver implementation.

**Comment by pjb236** [comment]
@eparish1 See pull request #84 for my first attempt at this.
