### ISSUE TITLE
fix test that sporadically hangs

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/rom-tools-and-workflows#91]
related to https://github.com/Pressio/rom-tools-and-workflows/issues/88, which test hangs? @jtencer

**Comment by jtencer** [comment]
It was one of the ecsw tests, but I think @pjb236 already fixed it.

**Comment by pjb236** [comment]
When did this happen and which test was it? I merged the pull request a day or two ago, so if this has been happening since, then something's still going on with ECSW. What a terrible algorithm.

**Comment by jtencer** [comment]
I haven't seen it since you merged the pull request.
