### ISSUE TITLE
Small improvements to truncater

### ISSUE THREAD

**Issue by eparish1** [Pressio/rom-tools-and-workflows#96]
- There's an extra description under EnergyTruncater that does not make sense. Also recommend an example or recommended value for the threshold.
- There should be a warning in BasisSizeTruncater if you try to truncate larger than  the actual size of the basis (or accidentally put a negative number or zero).
- General review of documentation

**Comment by eparish1** [comment]
@ekrathSNL Want to take a stab at this?

**Comment by ekrathSNL** [comment]
Sure!

**Comment by ekrathSNL** [comment]
This issue was fixed with pull #155 .
